### ISSUE TITLE
[Bug]: Formatting issues

### ISSUE THREAD

**Issue by Craftefix** [flytegg/plugin-portal#61] opened 2024-07-01 11:30 UTC
### Description

When using `/pp install ` it doesnt filter for special characters so it has some issues with folders and filesystems

### Minimal Reproduction

1.`/pp install Plan | Player Analytics`
   A temporary "fix" is using the `-byID` argunent

2.`/pp install eBackup - Simple and reliable backups for your server! Supports FTP/SFTP!`
   This always will save the plugin in _`eBackup - Simple and reliable backups for your server! Supports _FTP`_ with the jar named _`SFTP.jar`_

### Exception or Error

This bug will eventually create issues, especcially with feature #59 where the file could be saved in the unix/linux root dir "/" or user dir "~/"
When the plugin has a " | " in its name it ignores all arguments behind it, and says its the wrong source.
Also spaces can create issues with some plugins

### Dump

https://mclo.gs/0VKWqht

**Comment by Craftefix** [comment] 2024-07-01 11:31
The filder issue with ebackup got patched, but now it doesnt want to install at all, bc of a wrong source argunent

**Comment by MLGPenguin** [comment] 2024-07-01 11:31
This is a duplicate of both #51 and #58

**Comment by Craftefix** [comment] 2024-07-01 11:33
Yikes sorry for the work

**Comment by Dawsson** [comment] 2024-07-01 19:34
2 is fixed

**Comment by MLGPenguin** [comment] 2024-07-11 16:00
closes #51 and closes #58 

Fixed in latest snapshot

**Closed by MLGPenguin** 2024-07-11 16:00 UTC
Labels: bug
